export interface GameDocumentationCodeSample {
    label: string;
    language: "text" | "json" | "metta";
    content: string;
}

export interface GameDocumentationBlock {
    title: string;
    body?: string[];
    items?: string[];
    orderedItems?: string[];
    codeSamples?: GameDocumentationCodeSample[];
}

export interface GameDocumentationSection {
    id: "user-guide" | "technical-guide";
    label: string;
    title: string;
    summary: string;
    blocks: GameDocumentationBlock[];
}

export const gameDocumentationSections: GameDocumentationSection[] = [
    {
        id: "user-guide",
        label: "Player Guide",
        title: "Player Guide",
        summary: "How to play Emerald Grove Omen, read the interface, and solve the current island escape loop.",
        blocks: [
            {
                title: "Using The Client",
                body: [
                    "The Play panel is your narrative view. Type natural-language actions there and the server resolves them into MeTTa commands.",
                    "The Code panel is the direct MeTTa console. It shows the exact executed expressions, raw responses, and clickable definitions pulled from the backend startup catalog.",
                    "The notepad is for player note-taking only. It does not affect world state, but it is useful because rune locations and the final escape item can vary by run."
                ],
                items: [
                    "Use the Play tab for normal commands such as movement, examination, inventory, and item use.",
                    "Switch to the Code tab when you want to inspect the exact matched MeTTa or run explicit expressions like `!(inventory)`.",
                    "Click highlighted MeTTa in the Code panel to open the built-in definition inspector."
                ]
            },
            {
                title: "Command Patterns",
                body: [
                    "Natural-language matching is intentionally flexible, but the most reliable inputs follow the templates generated by the server command catalog."
                ],
                codeSamples: [
                    {
                        label: "Common player commands",
                        language: "text",
                        content: [
                            "inventory",
                            "look in satchel",
                            "pick up compass",
                            "examine locked cabin",
                            "go north",
                            "go to beach",
                            "use metal key on locked cabin",
                            "use oil on lantern",
                            "stay still"
                        ].join("\n")
                    }
                ],
                items: [
                    "Movement supports both directions and named destinations when reachable.",
                    "Containers must be accessible through the current location path before `look in` works.",
                    "Explicit MeTTa commands are allowed from the Code panel, but dangerous tokens are blocked and long-running commands are timed out by the runtime."
                ]
            },
            {
                title: "Recommended Play Loop",
                orderedItems: [
                    "Search the glade first. Pick up the satchel, then look inside it and take the compass. This removes the opening route blocks and starts proper exploration.",
                    "Map the island. The ridge leads to the statue puzzle and later the cave. The beach, hollow path, fork, forest path, campsite, and plane site each hide part of the solution.",
                    "Collect tools and clues. The shovel is in the big chest at the campsite. Disturbed soil on the shore path hides the iron box once you use the shovel on it.",
                    "Solve the ridge statues. The three runes spell EGO when placed correctly into the lion, eagle, and bear statues. Their container locations are randomized between several world containers.",
                    "Unlock the cabin on the hollow path. The metal key is hidden in the seashell on the beach. Once the cabin opens, inspect the fireplace and loose board for more progression items.",
                    "Prepare the lantern. Oil from the cabin fireplace combines with the lantern from the campsite chest to create a functioning lantern.",
                    "Handle the cave correctly. After the statues move the boulder, enter the cave and use the functioning lantern. When the bear appears, wait or stay still. Moving immediately causes a game over.",
                    "Use the revealed escape item. Each run reveals either the propeller for the boat or the battery for the plane. Bring the correct item to its matching vehicle to win."
                ]
            },
            {
                title: "Run-Specific Variations",
                items: [
                    "Rune placement is randomized across several containers, so container checks matter every run.",
                    "The cave reveals only one escape item per run: either the propeller or the battery.",
                    "The boat and plane descriptions change to hint which one is fixable in the current session.",
                    "If the game ends in victory or death, the current session is locked and you need New Game to start over."
                ]
            }
        ]
    },
    {
        id: "technical-guide",
        label: "Technical Guide",
        title: "Technical Guide",
        summary: "How the client, runtime, reasoning model, and MeTTa-backed world state fit together.",
        blocks: [
            {
                title: "Runtime Architecture",
                items: [
                    "The server `GameSession` builds a Python `World`, renders it to raw MeTTa, loads it into Hyperon, and immediately runs the startup trigger.",
                    "Every `FunctionDefinition` contributes both executable MeTTa and optional documentation metadata through `doc_tooltip`.",
                    "Natural-language commands are matched against a generated command catalog backed by sentence-transformer embeddings.",
                    "The websocket layer sends structured events so the client never has to parse raw MeTTa source to understand command results."
                ],
                codeSamples: [
                    {
                        label: "Startup event shape",
                        language: "json",
                        content: [
                            "{",
                            "  \"event\": \"startup\",",
                            "  \"metta_code\": \"...\",",
                            "  \"metta_docs\": [",
                            "    {",
                            "      \"id\": \"doc:1\",",
                            "      \"head\": \"inventory\",",
                            "      \"signature\": \"(inventory)\",",
                            "      \"source_metta\": \"(= (inventory) ...)\",",
                            "      \"kind\": \"function\",",
                            "      \"tooltip\": \"Lists the items and containers the player is currently carrying.\"",
                            "    }",
                            "  ]",
                            "}"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Command Processing Pipeline",
                orderedItems: [
                    "The client creates a payload with `command`, `command_type`, and a UUID, then sends it over the shared websocket connection.",
                    "For natural language, the server refreshes the command catalog from active world state and uses the embedding index to pick the best MeTTa command.",
                    "The runtime executes the matched MeTTa or explicit MeTTa query, resolves related documentation IDs, and formats both raw and player-facing responses.",
                    "Natural-language commands automatically run `!(synchronize-tick)` after the primary action so timed or procedural effects can advance.",
                    "The websocket response returns `queries[]`, each with `matched_metta`, `doc_ids`, `original_responses`, and cleaned `responses` for the UI."
                ],
                codeSamples: [
                    {
                        label: "Command result shape",
                        language: "json",
                        content: [
                            "{",
                            "  \"event\": \"command_result\",",
                            "  \"uuid\": \"123e4567-e89b-12d3-a456-426614174000\",",
                            "  \"queries\": [",
                            "    {",
                            "      \"command_type\": \"natural_language\",",
                            "      \"original_input\": \"look in satchel\",",
                            "      \"matched_metta\": \"!(look-in (satchel))\",",
                            "      \"doc_ids\": [\"doc:4\"],",
                            "      \"original_responses\": [\"(Response 20 \\\"Inside, an old compass rests against the lining.\\\")\"],",
                            "      \"responses\": [\"Inside, an old compass rests against the lining.\"]",
                            "    }",
                            "  ]",
                            "}"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Procedural Modules",
                items: [
                    "Compass module gates movement out of the glade until the player finds the compass, then prints route guidance after pickup and on later moves.",
                    "Cabin module defines the locked cabin, fireplace, loose board, and the metal-key unlock interaction.",
                    "Statues module randomizes rune placement, handles statue-slot state, and removes the cave entrance block when the EGO configuration is correct.",
                    "Cave module adds a custom `stay-still` verb, lantern usage, the bear threat state, and the death-or-survival branch.",
                    "Escape module randomizes which final repair item matters and writes the `GameWon` state when the player repairs the valid vehicle."
                ]
            },
            {
                title: "Client Integration Points",
                items: [
                    "The home page maintains gameplay log state, explicit-code console state, pending command UUIDs, and MeTTa documentation viewer history.",
                    "The client stores backend docs in a `MettaDocsStore` and resolves nested callable expressions without reparsing server source on the backend.",
                    "The MeTTa inspector supports history tabs, nested expression navigation, tooltips, and direct source inspection from executed console entries.",
                    "This documentation dialog is static client content and should be updated when the world builder, command catalog, or runtime protocol changes."
                ]
            },
            {
                title: "Reasoning In Practice",
                body: [
                    "The game is not a hard-coded command switch. Python definitions emit MeTTa source, and Hyperon evaluates that source against the current atomspace.",
                    "Each gameplay verb is a declarative rule. For example, movement checks current location state, route facts, and route blocks before triggering the move event."
                ],
                codeSamples: [
                    {
                        label: "Movement intent templates",
                        language: "text",
                        content: [
                            "go north",
                            "move north",
                            "head north",
                            "go to beach",
                            "walk to cave"
                        ].join("\n")
                    },
                    {
                        label: "Representative MeTTa definition style",
                        language: "metta",
                        content: [
                            "(= (inventory)",
                            "    (let $result (collapse (match &self (State (At $what player)) ...))",
                            "        (case $result (",
                            "            (() (Response 20 \"Your inventory is empty.\"))",
                            "            ($_ $result)",
                            "        ))",
                            "    )",
                            ")"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Memory Model",
                body: [
                    "Persistent game memory is modeled as `State`-wrapped facts. Item locations, player location, the current tick, puzzle progress, and end states all live in the same declarative memory space.",
                    "Side effects mutate that memory by adding and removing atoms instead of mutating Python objects directly inside the game loop."
                ],
                items: [
                    "Picking up an item removes `(State (At item place))` and adds `(State (At item player))`.",
                    "Unlocking the cabin removes the locked cabin state and places the cabin container into the world state.",
                    "The bear encounter adds both `(State (At bear cave))` and `(State (BearThreatPending player))`.",
                    "Winning or dying adds terminal state atoms that stop later commands from changing the world."
                ],
                codeSamples: [
                    {
                        label: "Representative state atoms",
                        language: "metta",
                        content: [
                            "(State (At player glade))",
                            "(State (At compass satchel))",
                            "(State (Tick 1))",
                            "(State (BearThreatPending player))",
                            "(State (GameWon \"You escaped.\"))"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Ticks, Consequences, And Safety",
                orderedItems: [
                    "A natural-language player action resolves to a MeTTa query and executes immediately.",
                    "After that, the runtime issues `!(synchronize-tick)` so deferred logic can react to the new world state.",
                    "The cave uses this pattern to make the bear threat meaningful across more than one action instead of resolving instantly.",
                    "If the player stays still, the pending threat is cleared and the bear is removed. If the player moves first, the pending threat becomes a `GameOver` fact."
                ],
                items: [
                    "Explicit MeTTa commands do not automatically run tick sync, which keeps debugging predictable.",
                    "Direct MeTTa execution is guarded by a denylist and a timeout to reduce unsafe or runaway evaluation paths."
                ],
                codeSamples: [
                    {
                        label: "Tick-related command",
                        language: "metta",
                        content: "!(synchronize-tick)"
                    }
                ]
            },
            {
                title: "How Documentation Becomes Interactive",
                orderedItems: [
                    "Backend startup builds a doc catalog from every `FunctionDefinition` and extracts exact `signature`, `source_metta`, `kind`, and `tooltip` fields.",
                    "When a command executes, the runtime resolves the matching documentation IDs and includes them in the websocket response.",
                    "The client stores those docs locally, highlights executed expressions, and opens exact definitions when a user clicks code in the console.",
                    "Nested callable expressions inside a definition are parsed again on the client so the inspector can chain deeper into related functions and triggers."
                ],
                items: [
                    "This is why the Code panel doubles as a learning surface for MeTTa, not just a debugging console.",
                    "The docs inspector is most useful when comparing a natural-language action to the MeTTa that actually executed."
                ]
            }
        ]
    }
];
