export interface GameDocumentationCodeSample {
    label: string;
    language: "text" | "json" | "metta";
    content: string;
}

export interface GameDocumentationBlock {
    title: string;
    body?: string[];
    items?: string[];
    orderedItems?: string[];
    codeSamples?: GameDocumentationCodeSample[];
}

export interface GameDocumentationSection {
    id: "user-guide" | "technical-guide" | "educational-material";
    label: string;
    title: string;
    summary: string;
    blocks: GameDocumentationBlock[];
}

export const gameDocumentationSections: GameDocumentationSection[] = [
    {
        id: "user-guide",
        label: "Player Guide",
        title: "Player Guide",
        summary: "How to play Emerald Grove Omen, read the interface, and solve the current island escape loop.",
        blocks: [
            {
                title: "Using The Client",
                body: [
                    "The Play panel is your narrative view. Type natural-language actions there and the server resolves them into MeTTa commands.",
                    "The Code panel is the direct MeTTa console. It shows the exact executed expressions, raw responses, and clickable definitions pulled from the backend startup catalog.",
                    "The notepad is for player note-taking only. It does not affect world state, but it is useful because rune locations and the final escape item can vary by run."
                ],
                items: [
                    "Use the Play tab for normal commands such as movement, examination, inventory, and item use.",
                    "Switch to the Code tab when you want to inspect the exact matched MeTTa or run explicit expressions like `!(inventory)`.",
                    "Click highlighted MeTTa in the Code panel to open the built-in definition inspector."
                ]
            },
            {
                title: "Command Patterns",
                body: [
                    "Natural-language matching is intentionally flexible, but the most reliable inputs follow the templates generated by the server command catalog."
                ],
                codeSamples: [
                    {
                        label: "Common player commands",
                        language: "text",
                        content: [
                            "inventory",
                            "look in satchel",
                            "pick up compass",
                            "examine locked cabin",
                            "go north",
                            "go to beach",
                            "use metal key on locked cabin",
                            "use oil on lantern",
                            "stay still"
                        ].join("\n")
                    }
                ],
                items: [
                    "Movement supports both directions and named destinations when reachable.",
                    "Containers must be accessible through the current location path before `look in` works.",
                    "Explicit MeTTa commands are allowed from the Code panel, but dangerous tokens are blocked and long-running commands are timed out by the runtime."
                ]
            },
            {
                title: "Recommended Play Loop",
                orderedItems: [
                    "Search the glade first. Pick up the satchel, then look inside it and take the compass. This removes the opening route blocks and starts proper exploration.",
                    "Map the island. The ridge leads to the statue puzzle and later the cave. The beach, hollow path, fork, forest path, campsite, and plane site each hide part of the solution.",
                    "Collect tools and clues. The shovel is in the big chest at the campsite. Disturbed soil on the shore path hides the iron box once you use the shovel on it.",
                    "Solve the ridge statues. The three runes spell EGO when placed correctly into the lion, eagle, and bear statues. Their container locations are randomized between several world containers.",
                    "Unlock the cabin on the hollow path. The metal key is hidden in the seashell on the beach. Once the cabin opens, inspect the fireplace and loose board for more progression items.",
                    "Prepare the lantern. Oil from the cabin fireplace combines with the lantern from the campsite chest to create a functioning lantern.",
                    "Handle the cave correctly. After the statues move the boulder, enter the cave and use the functioning lantern. When the bear appears, wait or stay still. Moving immediately causes a game over.",
                    "Use the revealed escape item. Each run reveals either the propeller for the boat or the battery for the plane. Bring the correct item to its matching vehicle to win."
                ]
            },
            {
                title: "Run-Specific Variations",
                items: [
                    "Rune placement is randomized across several containers, so container checks matter every run.",
                    "The cave reveals only one escape item per run: either the propeller or the battery.",
                    "The boat and plane descriptions change to hint which one is fixable in the current session.",
                    "If the game ends in victory or death, the current session is locked and you need New Game to start over."
                ]
            }
        ]
    },
    {
        id: "technical-guide",
        label: "Technical Guide",
        title: "Technical Guide",
        summary: "How the client, runtime, reasoning model, and MeTTa-backed world state fit together.",
        blocks: [
            {
                title: "Code Structure",
                body: [
                    "The backend is split between two parallel hierarchies, and understanding that split is the key to reading the codebase. `core/definitions/` holds objects that emit complete MeTTa statements; `core/patterns/` holds objects that emit MeTTa expressions used for matching inside those statements. Both expose a single `to_metta()` method.",
                    "The payoff is that atom shapes are defined once. `AtFactPattern` is the only place that knows an `At` fact is written `(At $what $where)`, so every rule that matches on it follows automatically from that one definition."
                ],
                codeSamples: [
                    {
                        label: "Backend — metta-game-server",
                        language: "text",
                        content: [
                            "main.py                   Entry point; CLI or websocket transport",
                            "core/",
                            "  runtime.py              GameSession: lifecycle, commands, safety",
                            "  world.py                World: definitions -> MeTTa source text",
                            "  world_builder.py        build_world(): the concrete scenario",
                            "  websocket_input.py      JSON protocol, healthcheck, server loop",
                            "  metta_doc_catalog.py    Extracts the clickable doc catalog",
                            "  definitions/            Objects that EMIT MeTTa source",
                            "    facts/                At, Character, Container, Item, Route",
                            "    functions/            inventory, move-to, pickup, drop, use,",
                            "                          look-in, examine, trigger, sync-tick",
                            "    side_effects/         on_move_update_at, on_game_won, ...",
                            "    wrappers/             State, Log, Stale",
                            "  patterns/               Objects that EMIT MeTTa expressions",
                            "    facts/ functions/ events/ wrappers/",
                            "  nlp/",
                            "    nl_spec.py            NLSpec / SlotSpec dataclasses",
                            "    command_catalog.py    Utterance -> MeTTa from live world state",
                            "    embedding_index.py    Sentence-transformer matcher",
                            "modules/                  Self-contained procedural units",
                            "  compass/ cabin/ statues/ cave/ escape/",
                            "utils/",
                            "  response.py             Parses MeTTa atoms into player text",
                            "tests/                    Automated suites mirroring the source"
                        ].join("\n")
                    },
                    {
                        label: "Frontend — metta-game-client",
                        language: "text",
                        content: [
                            "src/",
                            "  game/                   Pure logic, no React — unit tested",
                            "    game-protocol.ts      Wire types + validating event parser",
                            "    game-session-state.ts Reducer: events -> messages, console",
                            "    game-connection-state.ts  Socket state -> status label",
                            "    metta-docs.ts         MeTTa parser, doc store, click targets",
                            "    metta-doc-viewer-state.ts Inspector navigation history",
                            "  components/",
                            "    metta-code.tsx        Syntax highlighting for MeTTa",
                            "    metta-doc-inspector.tsx   Clickable definition browser",
                            "    game-documentation-dialog.tsx  This dialog",
                            "  content/",
                            "    game-documentation.ts The content you are reading now",
                            "  pages/home-page.tsx     Panels, tabs, input, dialog wiring"
                        ].join("\n")
                    }
                ],
                items: [
                    "A `Definition` emits a complete statement and is registered on the world. A `Pattern` emits an expression and is composed inside definitions.",
                    "Facts describe what exists, functions are the callable verbs, side effects are trigger bodies, and wrappers mark an atom's role.",
                    "Modules under `modules/` extend behaviour by registering additional triggers on existing events, so `core/` contains no reference to bears, lanterns, or caves.",
                    "On the client, all protocol and parsing logic lives in `src/game/` with no React dependency, which is why it can be unit tested directly."
                ]
            },
            {
                title: "Runtime Architecture",
                items: [
                    "The server `GameSession` builds a Python `World`, renders it to raw MeTTa, loads it into Hyperon, and immediately runs the startup trigger.",
                    "Every `FunctionDefinition` contributes both executable MeTTa and optional documentation metadata through `doc_tooltip`.",
                    "Natural-language commands are matched against a generated command catalog backed by sentence-transformer embeddings.",
                    "The websocket layer sends structured events so the client never has to parse raw MeTTa source to understand command results."
                ],
                codeSamples: [
                    {
                        label: "Startup event shape",
                        language: "json",
                        content: [
                            "{",
                            "  \"event\": \"startup\",",
                            "  \"metta_code\": \"...\",",
                            "  \"metta_docs\": [",
                            "    {",
                            "      \"id\": \"doc:1\",",
                            "      \"head\": \"inventory\",",
                            "      \"signature\": \"(inventory)\",",
                            "      \"source_metta\": \"(= (inventory) ...)\",",
                            "      \"kind\": \"function\",",
                            "      \"tooltip\": \"Lists the items and containers the player is currently carrying.\"",
                            "    }",
                            "  ]",
                            "}"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Command Processing Pipeline",
                orderedItems: [
                    "The client creates a payload with `command`, `command_type`, and a UUID, then sends it over the shared websocket connection.",
                    "For natural language, the server refreshes the command catalog from active world state and uses the embedding index to pick the best MeTTa command.",
                    "The runtime executes the matched MeTTa or explicit MeTTa query, resolves related documentation IDs, and formats both raw and player-facing responses.",
                    "Natural-language commands automatically run `!(synchronize-tick)` after the primary action so timed or procedural effects can advance.",
                    "The websocket response returns `queries[]`, each with `matched_metta`, `doc_ids`, `original_responses`, and cleaned `responses` for the UI."
                ],
                codeSamples: [
                    {
                        label: "Command result shape",
                        language: "json",
                        content: [
                            "{",
                            "  \"event\": \"command_result\",",
                            "  \"uuid\": \"123e4567-e89b-12d3-a456-426614174000\",",
                            "  \"queries\": [",
                            "    {",
                            "      \"command_type\": \"natural_language\",",
                            "      \"original_input\": \"look in satchel\",",
                            "      \"matched_metta\": \"!(look-in (satchel))\",",
                            "      \"doc_ids\": [\"doc:4\"],",
                            "      \"original_responses\": [\"(Response 20 \\\"Inside, an old compass rests against the lining.\\\")\"],",
                            "      \"responses\": [\"Inside, an old compass rests against the lining.\"]",
                            "    }",
                            "  ]",
                            "}"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Procedural Modules",
                items: [
                    "Compass module gates movement out of the glade until the player finds the compass, then prints route guidance after pickup and on later moves.",
                    "Cabin module defines the locked cabin, fireplace, loose board, and the metal-key unlock interaction.",
                    "Statues module randomizes rune placement, handles statue-slot state, and removes the cave entrance block when the EGO configuration is correct.",
                    "Cave module adds a custom `stay-still` verb, lantern usage, the bear threat state, and the death-or-survival branch.",
                    "Escape module randomizes which final repair item matters and writes the `GameWon` state when the player repairs the valid vehicle."
                ]
            },
            {
                title: "Client Integration Points",
                items: [
                    "The home page maintains gameplay log state, explicit-code console state, pending command UUIDs, and MeTTa documentation viewer history.",
                    "The client stores backend docs in a `MettaDocsStore` and resolves nested callable expressions without reparsing server source on the backend.",
                    "The MeTTa inspector supports history tabs, nested expression navigation, tooltips, and direct source inspection from executed console entries.",
                    "This documentation dialog is static client content and should be updated when the world builder, command catalog, or runtime protocol changes."
                ]
            },
            {
                title: "Reasoning In Practice",
                body: [
                    "The game is not a hard-coded command switch. Python definitions emit MeTTa source, and Hyperon evaluates that source against the current atomspace.",
                    "Each gameplay verb is a declarative rule. For example, movement checks current location state, route facts, and route blocks before triggering the move event."
                ],
                codeSamples: [
                    {
                        label: "Movement intent templates",
                        language: "text",
                        content: [
                            "go north",
                            "move north",
                            "head north",
                            "go to beach",
                            "walk to cave"
                        ].join("\n")
                    },
                    {
                        label: "Representative MeTTa definition style",
                        language: "metta",
                        content: [
                            "(= (inventory)",
                            "    (let $result (collapse (match &self (State (At $what player)) ...))",
                            "        (case $result (",
                            "            (() (Response 20 \"Your inventory is empty.\"))",
                            "            ($_ $result)",
                            "        ))",
                            "    )",
                            ")"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Memory Model",
                body: [
                    "Persistent game memory is modeled as `State`-wrapped facts. Item locations, player location, the current tick, puzzle progress, and end states all live in the same declarative memory space.",
                    "Side effects mutate that memory by adding and removing atoms instead of mutating Python objects directly inside the game loop."
                ],
                items: [
                    "Picking up an item removes `(State (At item place))` and adds `(State (At item player))`.",
                    "Unlocking the cabin removes the locked cabin state and places the cabin container into the world state.",
                    "The bear encounter adds both `(State (At bear cave))` and `(State (BearThreatPending player))`.",
                    "Winning or dying adds terminal state atoms that stop later commands from changing the world."
                ],
                codeSamples: [
                    {
                        label: "Representative state atoms",
                        language: "metta",
                        content: [
                            "(State (At player glade))",
                            "(State (At compass satchel))",
                            "(State (Tick 1))",
                            "(State (BearThreatPending player))",
                            "(State (GameWon \"You escaped.\"))"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "Ticks, Consequences, And Safety",
                orderedItems: [
                    "A natural-language player action resolves to a MeTTa query and executes immediately.",
                    "After that, the runtime issues `!(synchronize-tick)` so deferred logic can react to the new world state.",
                    "The cave uses this pattern to make the bear threat meaningful across more than one action instead of resolving instantly.",
                    "If the player stays still, the pending threat is cleared and the bear is removed. If the player moves first, the pending threat becomes a `GameOver` fact."
                ],
                items: [
                    "Explicit MeTTa commands do not automatically run tick sync, which keeps debugging predictable.",
                    "Direct MeTTa execution is guarded by a denylist and a timeout to reduce unsafe or runaway evaluation paths."
                ],
                codeSamples: [
                    {
                        label: "Tick-related command",
                        language: "metta",
                        content: "!(synchronize-tick)"
                    }
                ]
            },
            {
                title: "How Documentation Becomes Interactive",
                orderedItems: [
                    "Backend startup builds a doc catalog from every `FunctionDefinition` and extracts exact `signature`, `source_metta`, `kind`, and `tooltip` fields.",
                    "When a command executes, the runtime resolves the matching documentation IDs and includes them in the websocket response.",
                    "The client stores those docs locally, highlights executed expressions, and opens exact definitions when a user clicks code in the console.",
                    "Nested callable expressions inside a definition are parsed again on the client so the inspector can chain deeper into related functions and triggers."
                ],
                items: [
                    "This is why the Code panel doubles as a learning surface for MeTTa, not just a debugging console.",
                    "The docs inspector is most useful when comparing a natural-language action to the MeTTa that actually executed."
                ]
            }
        ]
    },
    {
        id: "educational-material",
        label: "Tutorials",
        title: "Tutorials",
        summary: "Learn MeTTa and Hyperon by taking apart the running game. Every query below can be executed in the Code panel.",
        blocks: [
            {
                title: "Before You Start",
                body: [
                    "These tutorials teach MeTTa by example, using the real rules of this game. Nothing here is simplified for illustration, and every query can be run against the live world.",
                    "Switch to the Code panel and keep it open. That panel is both the console you will type into and the place where executed MeTTa becomes clickable."
                ],
                items: [
                    "You do not need prior MeTTa experience.",
                    "Direct MeTTa commands do not advance the game clock, so you can inspect state freely without moving the world."
                ]
            },
            {
                title: "1. MeTTa In Five Minutes",
                body: [
                    "MeTTa has one data structure: the atom. An atom is a symbol, or a parenthesized list of atoms. `(At compass satchel)` is one atom containing three, and it has no built-in meaning — meaning comes from the rules written about it.",
                    "Atoms live in a knowledge graph called the atomspace. This game's is `&self`. At startup the server writes the entire world into it, and everything afterwards is a query against it or a change to it.",
                    "An atom starting with `$` is a variable. `match` searches for a shape and evaluates a template for each hit. `=` defines a rewrite rule, and every matching rule applies — the game depends on that. `!` marks an expression for evaluation."
                ],
                codeSamples: [
                    {
                        label: "The four forms you will keep seeing",
                        language: "metta",
                        content: [
                            "; search the atomspace",
                            "(match &self (State (At $what player)) $what)",
                            "",
                            "; branch on a result; Empty means no match",
                            "(case (match &self (RouteBlock $from $to $reason) $reason) (",
                            "    (Empty  ...nothing blocks the way...)",
                            "    ($reason ...answer with the reason...)",
                            "))",
                            "",
                            "; sequence steps; () bindings run for effect",
                            "(let* (($tick (match &self (State (Tick $t)) $t))",
                            "       (() (remove-atom &self (State (Tick $tick)))))",
                            "    Empty",
                            ")",
                            "",
                            "; gather all results of a multi-result expression",
                            "(collapse (match &self (State (At $what player)) $what))"
                        ].join("\n")
                    }
                ]
            },
            {
                title: "2. Watch A Command Compile",
                orderedItems: [
                    "In the Play panel, type `what am I carrying`.",
                    "Switch to the Code panel. You will see `!(inventory)` followed by `!(synchronize-tick)`. You wrote English; the server chose MeTTa by embedding your sentence and comparing it against every action currently possible.",
                    "Click the highlighted `inventory`. The inspector opens the real rule, exactly as the server generated it.",
                    "Read it from the middle outward: `(State (At $what player))` finds everything located on the player. There is no inventory list anywhere — inventory is a query over memory.",
                    "Follow the nested clickable calls deeper. The inspector keeps a breadcrumb trail so you can walk back up."
                ]
            },
            {
                title: "3. Representing A World As Knowledge",
                body: [
                    "One relation does most of the work. `At` expresses being at a location, being inside a container, and being carried — carrying is just being located at the player.",
                    "Because containment nests arbitrarily, `location-path` walks the chain recursively until it reaches something typed `Location`. That single rule is why picking up a compass inside a satchel on the ground works at all."
                ],
                codeSamples: [
                    {
                        label: "Containment, and the rule that walks it",
                        language: "metta",
                        content: [
                            "(State (At player glade))",
                            "(State (At satchel glade))",
                            "(State (At compass satchel))",
                            "",
                            "(= (location-path ($what))",
                            "    (let $where (match &self (State (At $what $where)) $where)",
                            "        (case (get-type $where) (",
                            "            (Location (Cons $where (Nil)))",
                            "            ($_ (Cons $where (location-path ($where))))",
                            "        ))",
                            "    )",
                            ")"
                        ].join("\n")
                    }
                ],
                items: [
                    "Facts without `State` are the world's definition and never change: `(Item compass)`, `(ItemName compass \"Compass\")`.",
                    "Facts inside `State` are the world's current condition and are rewritten constantly.",
                    "The rules themselves are atoms in the same atomspace as the facts. That is why this documentation inspector can exist at all."
                ]
            },
            {
                title: "4. Reasoning: How Movement Decides",
                body: [
                    "Reasoning here means deciding what is possible given current state. `move-towards` binds where you are, asks whether a route exists, asks whether it is blocked, and only then fires the move.",
                    "Notice that the rule never asks whether you have the compass. It asks whether a block exists. The compass module removes those blocks on pickup. The movement rule and the compass puzzle know nothing about each other — they meet through shared state."
                ],
                codeSamples: [
                    {
                        label: "The whole movement decision",
                        language: "metta",
                        content: [
                            "(= (move-towards ($direction))",
                            "    (match &self (State (At player $from))",
                            "        (case (match &self (Route $from $direction $to) $to)",
                            "        (",
                            "            (Empty (Response 100 \"You cannot go that way.\"))",
                            "            ($to (case (match &self (RouteBlock $from $to $reason) $reason)",
                            "            (",
                            "                (Empty (trigger (Move $from $to)))",
                            "                ($reason (Response 100 $reason))",
                            "            )))",
                            "        ))",
                            "    )",
                            ")"
                        ].join("\n")
                    }
                ],
                items: [
                    "`(trigger (Move $from $to))` does not perform the move. It asks the world what a move means, and every rule with a matching head answers.",
                    "Update location, mark the clock stale, print the description, arm the cave threat, resolve a pending death — all separate rules, all firing.",
                    "Adding a consequence to movement means adding a rule, never editing one. That is how the cave adds mortal danger without the movement rule ever mentioning bears."
                ]
            },
            {
                title: "5. Memory: Change Is Atom Rewriting",
                body: [
                    "There is no save file, no state object, no dictionary of variables. Memory is the set of `State` atoms, and every change is an `add-atom` or a `remove-atom`.",
                    "Run the query below, pick up the compass in the Play panel, then run it again. One atom was removed and one was added. That is the entire mechanism, and it is the same for every change in the game."
                ],
                codeSamples: [
                    {
                        label: "Watch memory change",
                        language: "metta",
                        content: "!(match &self (State (At compass $where)) $where)"
                    },
                    {
                        label: "The complete effect of picking something up",
                        language: "metta",
                        content: [
                            "(let* (($current_tick (match &self (State (Tick $tick)) $tick))",
                            "    ( ()  (add-atom &self (Log $current_tick (PickUp compass $where))))",
                            "    ( ()  (match &self (State (At compass $where_match))",
                            "        (remove-atom &self (State (At compass $where_match)))))",
                            "    ( ()  (add-atom &self (State (At compass player)))))",
                            "    Empty",
                            ")"
                        ].join("\n")
                    }
                ],
                items: [
                    "`State` is what is true now, and is overwritten.",
                    "`Log` is what happened and when, accumulates, and is never erased. `move-to` consults it — you can only travel by name to somewhere you have been.",
                    "`Stale` marks that the clock owes an increment.",
                    "Every puzzle is memory, not code. `(statues-solved)` is a query over placed runes, not a flag."
                ]
            },
            {
                title: "6. Time And Deferred Consequence",
                body: [
                    "Some things should not resolve instantly. A bear in the dark should create a moment of decision — and a moment requires that the world can say something is pending, then react to what you do next.",
                    "Actions that consume time add `(Stale Tick)`. After every natural-language command the runtime issues `!(synchronize-tick)`, which advances the clock only if a stale marker exists. Your action happens, then the world settles."
                ],
                orderedItems: [
                    "In the lit cave, using the lantern adds `(State (At bear cave))` and `(State (BearThreatPending player))`. Nothing has attacked you — a fact has been asserted about the situation.",
                    "Two rules are now waiting, and your next action decides which matches.",
                    "If you move: the threat atom is removed and `(State (GameOver ...))` is added. You die.",
                    "If you stay still: the threat atom is removed and the bear is removed. You live.",
                    "Both rules begin by checking the same atom and both consume it. What differs is what replaces it."
                ],
                items: [
                    "There is no timer, no scheduler, no event queue, no state machine. The danger is one atom, and two rules disagree about what it means.",
                    "`stay still` outside the cave hits the fallback branch and simply prints \"You hold still for a moment.\" Same verb, different meaning, decided by state.",
                    "Run `!(match &self (State (Tick $t)) $t)`, move once, run it again — it advanced. Run a direct MeTTa command and check again — it did not."
                ]
            },
            {
                title: "7. Procedural Generation As Fact Placement",
                body: [
                    "Two things are randomized per session: which three of six containers hide the runes, and whether the cave yields the propeller or the battery.",
                    "The randomness lands in exactly one place — which `(State (At ...))` atoms get asserted. The rules governing runes are identical every run. What varies is a fact, not a behaviour. The rules do not know they are in a randomized world; they query state, and state happens to differ."
                ],
                codeSamples: [
                    {
                        label: "Prove it — find this run's hiding place",
                        language: "metta",
                        content: "!(match &self (State (At epsilon_rune $where)) $where)"
                    }
                ]
            },
            {
                title: "8. Exercises",
                body: [
                    "Run these in the Code panel. Each one states what you should observe."
                ],
                codeSamples: [
                    {
                        label: "Read your own location",
                        language: "metta",
                        content: "!(match &self (State (At player $where)) $where)"
                    },
                    {
                        label: "Discover the whole map, including places you have not visited",
                        language: "metta",
                        content: "!(match &self (Route $from $direction $to) ($from $direction $to))"
                    },
                    {
                        label: "Prove the compass puzzle is just deleted facts (run before and after pickup)",
                        language: "metta",
                        content: "!(match &self (RouteBlock glade $to $reason) $to)"
                    },
                    {
                        label: "Trace containment (compare before and after picking the compass up)",
                        language: "metta",
                        content: "!(location-path (compass))"
                    },
                    {
                        label: "Read your own history — the memory that move-to consults",
                        language: "metta",
                        content: "!(match &self (Log $tick $event) ($tick $event))"
                    },
                    {
                        label: "Check a puzzle without solving it",
                        language: "metta",
                        content: [
                            "!(statues-solved)",
                            "!(all-statues-filled)"
                        ].join("\n")
                    },
                    {
                        label: "Look at pending danger as a data point (True only in the lit cave)",
                        language: "metta",
                        content: "!(exists (State (BearThreatPending player)))"
                    }
                ]
            },
            {
                title: "Glossary",
                items: [
                    "`Atom` — the single data structure of MeTTa: a symbol, or a parenthesized list of atoms.",
                    "`Atomspace` — the knowledge graph atoms live in. This game's is `&self`.",
                    "`match` — search the atomspace for a shape and evaluate a template per hit.",
                    "`=` — defines a rewrite rule. All matching rules apply.",
                    "`collapse` — gathers all results of a multi-result expression into one list.",
                    "`State` — wrapper marking an atom as present-tense, mutable memory.",
                    "`Log` — wrapper recording that an event happened at a given tick.",
                    "`Stale` — wrapper marking that the clock owes an increment.",
                    "`Response` — atom carrying player-facing text with a display priority.",
                    "Trigger — a rule answering `(trigger <event>)`. Many may match one event.",
                    "Tick — the world clock, advanced by `synchronize-tick` after timed actions."
                ]
            }
        ]
    }
];
